#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>
#include <YSI\y_hooks>

main()
{
	print("\n----------------------------------");
	print(" Blank Gamemode by your name here");
	print("----------------------------------\n");
}

